# Generated by Django 4.0.2 on 2022-02-17 07:25

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('interview_scheduler', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interviewer',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 2, 17, 7, 25, 3, 417284, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='student',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 2, 17, 7, 25, 3, 416284, tzinfo=utc)),
        ),
    ]
