# Generated by Django 4.0.2 on 2022-02-17 07:32

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('interview_scheduler', '0002_alter_interviewer_date_alter_student_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='interviewer',
            old_name='time_slot',
            new_name='from_date',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='time_slot',
            new_name='from_date',
        ),
        migrations.AddField(
            model_name='interviewer',
            name='to_date',
            field=models.CharField(choices=[(9, '09:00 AM'), (10, '10:00 AM'), (11, '11:00 AM'), (12, '12:00 PM'), (13, '01:00 PM'), (14, '02:00 PM'), (15, '03:00 PM'), (16, '04:00 PM'), (17, '05:00 PM'), (18, '06:00 PM'), (19, '07:00 PM')], default='10', max_length=2),
        ),
        migrations.AddField(
            model_name='student',
            name='to_date',
            field=models.CharField(choices=[(9, '09:00 AM'), (10, '10:00 AM'), (11, '11:00 AM'), (12, '12:00 PM'), (13, '01:00 PM'), (14, '02:00 PM'), (15, '03:00 PM'), (16, '04:00 PM'), (17, '05:00 PM'), (18, '06:00 PM'), (19, '07:00 PM')], default='10', max_length=2),
        ),
        migrations.AlterField(
            model_name='interviewer',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 2, 17, 7, 32, 41, 310800, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='student',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 2, 17, 7, 32, 41, 310800, tzinfo=utc)),
        ),
    ]
