# Generated by Django 4.0.2 on 2022-02-17 12:01

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('interview_scheduler', '0004_remove_interviewer_from_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='interviewer',
            old_name='from_time',
            new_name='from_date',
        ),
        migrations.RenameField(
            model_name='interviewer',
            old_name='to_time',
            new_name='to_date',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='from_time',
            new_name='from_date',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='to_time',
            new_name='to_date',
        ),
        migrations.AlterField(
            model_name='interviewer',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 2, 17, 12, 0, 53, 658972, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='student',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 2, 17, 12, 0, 53, 657972, tzinfo=utc)),
        ),
    ]
